version: "3.1"
# https://docs.docker.com/compose/compose-file/

services:
  nginx:
    image: phpkube/nginx
    tty: true
    ports:
    - 8080:8080
    volumes:
      - ./data:/home/phpkube/html/

  php-fpm:
    image: phpkube/php-fpm
    tty: true
    ports:
    - 9000:9000
    volumes:
      - ./data:/home/phpkube/html/
